### ISSUE TITLE
(adapter)예외는 서비스에서 던져주세요!!

### ISSUE THREAD

**Issue by 10kseok** [nhnacademy-be3-CookShoong/cookshoong-frontend#45]
예외는 서비스에서 던져주세요!!

_Originally posted by @10kseok in https://github.com/nhnacademy-be3-CookShoong/cookshoong-frontend/pull/43#discussion_r1263440283_

**Comment by Dendroh** [comment]
서비스에서 예외를 처리하도록 어뎁터에서 예외처리를 제거하였습니다.
